server:
  port: 10000
spring:
  application:
    name: gateway-service
  cloud:
    consul:
#      host: http://107.179.13.169
      host: http://localhost
      port: 8500
      config:
        enabled: true
        format: yaml